export function generateDeveloperJourney() {
  return {
    nodes: [
      { name: 'Documentation Overview', category: 'discovery', value: 100 },
      { name: 'API Reference', category: 'discovery', value: 95 },
      { name: 'Getting Started Guide', category: 'discovery', value: 90 },
      { name: 'Quick Start Tutorials', category: 'discovery', value: 85 },
      { name: 'Interactive Tutorials', category: 'learning', value: 80 },
      { name: 'Code Examples', category: 'learning', value: 75 },
      { name: 'Video Guides', category: 'learning', value: 70 },
      { name: 'Developer Workshops', category: 'learning', value: 65 },
      { name: 'Sample Projects', category: 'building', value: 60 },
      { name: 'Integration Guides', category: 'building', value: 55 },
      { name: 'API Implementation', category: 'building', value: 50 },
      { name: 'Testing Tools', category: 'building', value: 45 },
      { name: 'Issue Reporting', category: 'contributing', value: 40 },
      { name: 'Pull Requests', category: 'contributing', value: 35 },
      { name: 'Code Reviews', category: 'contributing', value: 30 },
      { name: 'Documentation Updates', category: 'contributing', value: 25 },
      { name: 'Community Leadership', category: 'leading', value: 20 },
      { name: 'Technical Talks', category: 'leading', value: 15 },
      { name: 'Mentoring', category: 'leading', value: 10 },
      { name: 'Open Source Projects', category: 'leading', value: 5 },
    ],
    links: [
      { source: 0, target: 4, value: 50 },
      { source: 1, target: 5, value: 45 },
      { source: 2, target: 6, value: 40 },
      { source: 3, target: 7, value: 35 },
      { source: 4, target: 8, value: 40 },
      { source: 5, target: 9, value: 35 },
      { source: 6, target: 10, value: 30 },
      { source: 7, target: 11, value: 25 },
      { source: 8, target: 12, value: 30 },
      { source: 9, target: 13, value: 25 },
      { source: 10, target: 14, value: 20 },
      { source: 11, target: 15, value: 15 },
      { source: 12, target: 16, value: 20 },
      { source: 13, target: 17, value: 15 },
      { source: 14, target: 18, value: 10 },
      { source: 15, target: 19, value: 5 },
      { source: 1, target: 10, value: 20 },
      { source: 5, target: 13, value: 15 },
      { source: 7, target: 17, value: 10 },
      { source: 14, target: 18, value: 5 },
      { source: 0, target: 1, value: 40 },
      { source: 0, target: 2, value: 35 },
      { source: 0, target: 3, value: 30 },
      { source: 4, target: 5, value: 25 },
      { source: 5, target: 6, value: 20 },
      { source: 6, target: 7, value: 15 },
      { source: 8, target: 9, value: 20 },
      { source: 9, target: 10, value: 15 },
      { source: 10, target: 11, value: 10 },
      { source: 12, target: 13, value: 15 },
      { source: 13, target: 14, value: 10 },
      { source: 14, target: 15, value: 5 },
      { source: 16, target: 17, value: 10 },
      { source: 17, target: 18, value: 8 },
      { source: 18, target: 19, value: 5 },
    ],
  }
}
